export const MERGE_QUERY_PARAM = 'MERGE_DEPENDABOT_PR';

export const WAIT_PERIODS = {
  CLICK_BUTTON: 250,
  CLOSE_TAB: 5000,
  OPEN_NEW_TAB: 1500,
};

export default {
  MERGE_QUERY_PARAM,
  WAIT_PERIODS,
};
