export const MERGE_QUERY_PARAM = 'MERGE_DEPENDABOT_PR';

export const WAIT_PERIODS = {
  CLICK_BUTTON: 500,
  CLOSE_TAB: 7000,
  OPEN_NEW_TAB: 3000,
};

export default {
  MERGE_QUERY_PARAM,
  WAIT_PERIODS,
};
